/** A Sintonía spectrum: two opposite poles the dial runs between. */
export interface Spectrum {
    /** Left pole (dial at 0%). */
    left: string;
    /** Right pole (dial at 100%). */
    right: string;
}

/**
 * Los espectros de Sintonía: parejas de polos opuestos entre los que corre el dial.
 * Mezcla de conceptos concretos (Frío/Caliente) y, sobre todo, subjetivos y
 * discutibles (Sobrevalorado/Infravalorado, Cutre/Elegante) para picar debate.
 * Español de España, aptos para todos los públicos.
 */
export const WAVELENGTH_SPECTRUMS: Spectrum[] = [
    // --- Concretos / físicos ---
    { left: 'Frío', right: 'Caliente' },
    { left: 'Pequeño', right: 'Grande' },
    { left: 'Lento', right: 'Rápido' },
    { left: 'Ligero', right: 'Pesado' },
    { left: 'Vacío', right: 'Lleno' },
    { left: 'Oscuro', right: 'Luminoso' },
    { left: 'Silencioso', right: 'Ruidoso' },
    { left: 'Blando', right: 'Duro' },
    { left: 'Seco', right: 'Mojado' },
    { left: 'Suave', right: 'Áspero' },
    { left: 'Corto', right: 'Largo' },
    { left: 'Estrecho', right: 'Ancho' },
    { left: 'Nuevo', right: 'Viejo' },
    { left: 'Limpio', right: 'Sucio' },
    { left: 'Cerca', right: 'Lejos' },

    // --- Carácter / personalidad ---
    { left: 'Tímido', right: 'Extrovertido' },
    { left: 'Perezoso', right: 'Trabajador' },
    { left: 'Tacaño', right: 'Generoso' },
    { left: 'Serio', right: 'Gracioso' },
    { left: 'Cobarde', right: 'Valiente' },
    { left: 'Egoísta', right: 'Altruista' },
    { left: 'Optimista', right: 'Pesimista' },
    { left: 'Impulsivo', right: 'Calculador' },
    { left: 'Ordenado', right: 'Desordenado' },
    { left: 'Puntual', right: 'Impuntual' },
    { left: 'Modesto', right: 'Presumido' },
    { left: 'Sensato', right: 'Alocado' },
    { left: 'Rígido', right: 'Flexible' },
    { left: 'Ingenuo', right: 'Astuto' },
    { left: 'Torpe', right: 'Habilidoso' },
    { left: 'Sensible', right: 'Insensible' },
    { left: 'Formal', right: 'Informal' },
    { left: 'Reservado', right: 'Cotilla' },

    // --- Subjetivo / gusto / social (los más discutibles) ---
    { left: 'Sobrevalorado', right: 'Infravalorado' },
    { left: 'Cutre', right: 'Elegante' },
    { left: 'Normal', right: 'Raro' },
    { left: 'Aburrido', right: 'Divertido' },
    { left: 'Antiguo', right: 'Moderno' },
    { left: 'Sano', right: 'Insano' },
    { left: 'Íntimo', right: 'Público' },
    { left: 'De pobres', right: 'De ricos' },
    { left: 'Fácil', right: 'Difícil' },
    { left: 'Feo', right: 'Bonito' },
    { left: 'Poco romántico', right: 'Muy romántico' },
    { left: 'Mal rollo', right: 'Buen rollo' },
    { left: 'Cringe', right: 'Guay' },
    { left: 'Inútil', right: 'Útil' },
    { left: 'Placer culpable', right: 'Orgullo confesable' },
    { left: 'Básico', right: 'Sofisticado' },
    { left: 'Hortera', right: 'Con clase' },
    { left: 'Infantil', right: 'Maduro' },
    { left: 'Barato', right: 'Caro' },
    { left: 'Común', right: 'Exótico' },
    { left: 'Soso', right: 'Con chispa' },
    { left: 'Predecible', right: 'Sorprendente' },
    { left: 'Relajante', right: 'Estresante' },
    { left: 'Sobrio', right: 'Excesivo' },
    { left: 'Discreto', right: 'Llamativo' },
    { left: 'Amateur', right: 'Profesional' },
    { left: 'Cursi', right: 'Épico' },
    { left: 'Ordinario', right: 'Especial' },
    { left: 'Minimalista', right: 'Recargado' },
    { left: 'Clásico', right: 'Rompedor' },
    { left: 'Vintage', right: 'Futurista' },
    { left: 'Mainstream', right: 'Alternativo' },
    { left: 'Comercial', right: 'De culto' },
    { left: 'Sobrado', right: 'Humilde' },
    { left: 'Correcto', right: 'Gamberro' },
    { left: 'Tranquilo', right: 'Fiestero' },
    { left: 'Sedentario', right: 'Aventurero' },
    { left: 'Necesario', right: 'Innecesario' },
    { left: 'Esencial', right: 'Prescindible' },
    { left: 'Adictivo', right: 'Olvidable' },
    { left: 'Peligroso', right: 'Seguro' },
    { left: 'Arriesgado', right: 'Prudente' },
    { left: 'Monótono', right: 'Emocionante' },
    { left: 'Frágil', right: 'Resistente' },
    { left: 'Débil', right: 'Fuerte' },
    { left: 'Comida sana', right: 'Comida basura' },
    { left: 'Salado', right: 'Dulce' },
    { left: 'Insípido', right: 'Sabroso' },
    { left: 'Práctico', right: 'Vistoso' },
    { left: 'Superficial', right: 'Profundo' },
    { left: 'Ñoño', right: 'Bestia' },
    { left: 'Empalagoso', right: 'Distante' },
    { left: 'Rancio', right: 'Fresco' },
    { left: 'Muermo', right: 'Marchoso' },
    { left: 'Chapuza', right: 'Obra maestra' },
    { left: 'Genérico', right: 'Único' },
    { left: 'Corriente', right: 'Legendario' },
    { left: 'De moda', right: 'Pasado de moda' },
    { left: 'Anónimo', right: 'Famoso' },
    { left: 'Ridículo', right: 'Impresionante' },
    { left: 'Absurdo', right: 'Genial' },
    { left: 'Deprimente', right: 'Motivador' },
    { left: 'Bajona', right: 'Subidón' },
    { left: 'Melancólico', right: 'Eufórico' },
    { left: 'Tenso', right: 'Distendido' },
    { left: 'Incómodo', right: 'Cómodo' },
    { left: 'Agobiante', right: 'Liberador' },
    { left: 'De buen gusto', right: 'De mal gusto' },
    { left: 'Apropiado', right: 'Inapropiado' },
    { left: 'Educado', right: 'Maleducado' },
    { left: 'Justo', right: 'Injusto' },
    { left: 'Simpático', right: 'Antipático' },
    { left: 'Enrollado', right: 'Estirado' },
    { left: 'Sencillo', right: 'Complicado' },
    { left: 'Intuitivo', right: 'Lioso' },
    { left: 'Chollo', right: 'Timo' },
    { left: 'De saldo', right: 'De lujo' },
    { left: 'Viral', right: 'Ignorado' },
    { left: 'Vergüenza ajena', right: 'Admiración' },
];
