import './globals.css';

import { ClassnameHelper } from '@/helpers/clean-classname.helper';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Providers } from './providers';

const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-montserrat',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={ClassnameHelper.join('dark', montserrat.variable)}>
            <body className="antialiased">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
