/**
 * Chispas prompts (español de España). Each invites a short, funny written answer.
 * Kept as a flat list; the game picks pairs of players and assigns prompts at random.
 */
export const CHISPAS_PROMPTS: string[] = [
    'Lo primero que harías si te tocara la lotería',
    'El peor nombre para un restaurante',
    'Una mala excusa para llegar tarde al trabajo',
    'El superpoder más inútil del mundo',
    'Lo que NUNCA deberías decir en una primera cita',
    'El título de la autobiografía de tu jefe',
    'Lo que piensa tu gato mientras te mira dormir',
    'Una app que absolutamente nadie ha pedido',
    'El peor regalo para tu suegra',
    'Lo que dirías si te despiertas siendo el presidente del gobierno',
    'El nombre de un grupo de música formado por tus vecinos',
    'Una nueva asignatura obligatoria en el colegio',
    'El peor lema para una funeraria',
    'Lo que gritarías justo antes de saltar de un avión',
    'Un mal nombre para un perro que parezca peligroso',
    'La peor frase para tatuarte en el cuello',
    'Lo que de verdad significa "te lo miro y te digo algo"',
    'El título de una peli de terror ambientada en tu oficina',
    'Una excusa terrible para no ir a una boda',
    'El eslogan de una marca de calcetines',
    'Lo que hace tu madre con el móvil a las tres de la mañana',
    'Lo que pondrías en tu currículum si no supieras hacer nada',
    'Un plato nuevo para la carta de un bar de mala muerte',
    'Lo que pondrías en el cartel de "Se busca" de tu compañero de piso',
    'La última frase que dirías antes de que se acabe el mundo',
    'El nombre de una colonia con el peor olor posible',
    'Lo que piensa el perro cuando te vas de casa',
    'Una norma absurda para tu comunidad de vecinos',
    'El peor consejo para una pareja recién casada',
    'Un nuevo sabor de helado que jamás triunfaría',
    'Lo que escribe tu grupo de WhatsApp familiar a las ocho de la mañana',
    'El título de un documental sobre tu vida un domingo por la tarde',
    'Una mala idea para un parque de atracciones',
    'El nombre de un villano de dibujos animados inspirado en tu ex',
    'Lo que gritas cuando pisas un Lego descalzo',
    'El peor souvenir para traerte de vacaciones',
    'Una excusa para no devolver el dinero que te han prestado',
    'El eslogan de una campaña para comer más brócoli',
    'Lo que susurra el wifi justo cuando más lo necesitas',
    'Un mal nombre para una guardería',
    'El peor momento para que suene tu alarma',
    'Lo que diría tu nevera si pudiera hablar',
    'Una nueva prueba imposible para el carnet de conducir',
    'El título de una canción de reguetón sobre hacer la colada',
    'Lo que NUNCA hay que buscar en Google',
    'El peor tema para una charla TED',
    'Un producto de teletienda condenado al fracaso',
    'Lo que piensa el camarero cuando pides "lo de siempre"',
    'El nombre artístico que usarías como mago cutre',
    'Una mala frase para romper el hielo en un ascensor',
    'El peor disfraz para ir a una entrevista de trabajo',
    'Lo que harías con un clon tuyo durante un día',
    'El eslogan de una ciudad que no quiere visitar nadie',
    'Una tradición nueva y absurda para tu familia',
    'El título de una serie de Netflix sobre tu vida sentimental',
    'Lo que dice tu estómago en mitad de una reunión importante',
    'Un mal superpoder para tener en una primera cita',
    'El peor nombre para un yate de lujo',
    'Lo que gritarías al ganar la lotería en mitad de la calle',
    'Una excusa para escaquearte de una mudanza',
    'El nombre de una banda de heavy metal formada por jubilados',
    'Lo que piensa tu planta justo antes de morir',
    'El peor eslogan para una compañía aérea',
    'Una nueva función inútil para tu móvil',
    'Lo que dirías si te encuentras a tu jefe en la playa',
    'El título de un libro de autoayuda que no ayuda a nadie',
    'El peor nombre para un caballo de carreras',
    'Lo que hace tu compañero de trabajo cuando cree que nadie lo ve',
    'Un mal regalo para un amigo invisible',
    'El eslogan para vender paraguas en el desierto',
    'Lo que piensa el conductor del autobús a las siete de la mañana',
    'Una excusa terrible para no contestar a un mensaje',
    'El nombre de un perfume inspirado en tu portal',
    'El peor momento para quedarte sin batería',
    'Lo que dirías al abrir la puerta y encontrarte a tu ex',
    'Una nueva categoría para los premios Goya',
    'El título de una peli romántica ambientada en el Mercadona',
    'Lo que grita tu vecino a través de la pared',
    'Un mal nombre para un barco pesquero',
    'El peor superpoder para llevar a la playa',
    'Lo que piensa tu maleta dando vueltas en la cinta del aeropuerto',
    'Una excusa para no ir a la cena de empresa',
    'El eslogan de una marca de pañuelos para el desamor',
    'Lo que dirías en una boda si te toca hablar sin haberlo preparado',
    'El nombre de una startup que quebrará en un mes',
    'Un mal consejo para tu primer día de universidad',
    'Lo que hace tu móvil cuando no lo estás mirando',
    'El peor sitio para esconder un regalo de cumpleaños',
    'Una palabra nueva que debería existir en el diccionario',
    'Lo que diría tu horóscopo un lunes por la mañana',
    'El peor momento para que se pare el ascensor',
    'Una excusa para no prestar tu cargador',
    'El peor nombre para una cafetería',
    'Lo que gritarías sin querer en mitad de un funeral',
    'Un mal eslogan para un banco',
    'Lo que dice tu despertador cuando lo apagas por quinta vez',
    'El nombre de una montaña rusa pensada para dar miedo de verdad',
    'Una nueva red social que no usaría nadie',
    'El peor superpoder para un ladrón',
    'El nombre que le pondrías a tu coche',
    'Una excusa para no pagar tu ronda',
    'El título de un musical sobre hacer la declaración de la renta',
    'Lo que dirías si un extraterrestre te invita a su planeta',
    'El nombre de un helado que solo comprarías borracho',
    'Un mal lema para un equipo de fútbol',
    'Lo que susurra tu almohada cuando por fin te acuestas',
    'El peor sitio para tener un flechazo',
    'Una nueva olimpiada de deportes absurdos',
    'El título de un true crime sobre quién ha dejado los platos sin fregar',
    'El peor sitio para guardar tus ahorros',
    'Una excusa para no quedar el viernes por la noche',
    'El nombre de una peluquería para calvos',
    'Lo que gritarías al ver una araña gigante en la ducha',
    'Un mal invento para vender en la teletienda de madrugada',
    'El peor eslogan para unas vacaciones en familia',
    'Lo que piensa tu profesor mientras corrige tu examen',
    'Una nueva ley absurda que aprobarías si mandaras un solo día',
    'El título de una peli de acción protagonizada por tu abuela',
    'Lo que dirías si te quedas encerrado en un probador',
    'El nombre de una boy band montada en tu barrio',
    'Un mal souvenir para regalarle a tu jefe',
    'Una nueva señal de tráfico que hace falta de verdad',
    'Una excusa para escaquearte de fregar los platos',
    'El peor nombre para una peli de superhéroes',
    'Lo que dice tu báscula cada mañana',
    'Un nuevo emoji que hace muchísima falta',
    'El título de un reality sobre tu grupo de amigos',
    'Lo que gritarías en un coche que se queda sin frenos',
    'El peor sitio para quedarte dormido',
    'Una excusa para no ir al gimnasio en enero',
    'El nombre de un pueblo perdido en mitad de la nada',
    'Lo que piensa el repartidor de comida cuando llega a tu puerta',
    'El peor lema para una marca de compresas',
    'El título de una comedia romántica sobre dos personas atrapadas en el metro',
    'Lo que dirías si te reencarnas en el perro de tu vecino',
    'El nombre de una discoteca a la que no iría nadie',
    'Una excusa nueva para no cogerle el teléfono a tu madre',
    'El peor superpoder para un socorrista',
    'Lo que piensa el último trozo de pizza en la caja',
    'El nombre de un chiringuito de playa que da penita',
];
