/**
 * La Bomba categories (español de España). Each must have MANY easy answers so players
 * can rattle them off fast under pressure. Phrased as "Di un/una..." style prompts.
 */
export const BOMBA_CATEGORIES: string[] = [
    // Concrete lists — brands, places, names, animals
    'Marcas de coche',
    'Marcas de móvil',
    'Marcas de ropa',
    'Marcas de zapatillas',
    'Marcas de comida rápida',
    'Países de Europa',
    'Países de América',
    'Capitales europeas',
    'Ciudades de España',
    'Ríos',
    'Nombres de chico',
    'Nombres de chica',
    'Animales con cuatro patas',
    'Animales de granja',
    'Animales del mar',
    'Animales de la selva',
    'Pájaros',
    'Insectos',
    'Razas de perro',
    'Flores',
    'Árboles',
    'Frutas',
    'Verduras',
    'Partes del cuerpo',
    'Colores',
    'Deportes',
    'Profesiones',
    'Instrumentos musicales',
    'Superhéroes',
    'Personajes de dibujos animados',
    'Personajes de Disney',
    'Películas de superhéroes',
    'Equipos de fútbol',
    'Jugadores de fútbol',
    'Tenistas famosos',
    'Actores de Hollywood',
    'Actores españoles',
    'Cantantes españoles',
    'Grupos de música',
    'Canciones que todo el mundo se sabe',
    'Series de Netflix',
    'Videojuegos',
    'Apps del móvil',
    'Redes sociales',

    // Comida y bebida
    'Postres',
    'Tipos de pasta',
    'Ingredientes de una pizza',
    'Sabores de helado',
    'Tapas españolas',
    'Platos típicos españoles',
    'Tipos de pan',
    'Quesos',
    'Especias',
    'Cereales de desayuno',
    'Chuches y golosinas',
    'Refrescos',
    'Tipos de café',
    'Frutos secos',
    'Salsas',
    'Bebidas alcohólicas',
    'Cosas que se ponen en una tostada',

    // Cosas que hay en un sitio
    'Cosas que hay en una cocina',
    'Cosas que hay en un baño',
    'Cosas que hay en una playa',
    'Cosas que hay en una nevera',
    'Cosas que hay en clase',
    'Cosas que hay en un hospital',
    'Cosas que hay en el cielo',
    'Cosas que hay en un parque',
    'Cosas que hay en el garaje',
    'Cosas que hay en una oficina',
    'Cosas que hay en un supermercado',
    'Cosas que hay en una boda',
    'Cosas que hay en un cumpleaños',
    'Cosas que hay en el campo',
    'Cosas que hay en una feria',
    'Cosas que hay en una piscina',
    'Cosas que hay en un aeropuerto',
    'Cosas que hay en una farmacia',
    'Cosas que hay en un botiquín',
    'Cosas que llevas en la mochila',
    'Cosas que hay en tu mesita de noche',
    'Cosas que compras en el chino',

    // Sensoriales
    'Cosas rojas',
    'Cosas amarillas',
    'Cosas verdes',
    'Cosas azules',
    'Cosas blancas',
    'Cosas negras',
    'Cosas redondas',
    'Cosas cuadradas',
    'Cosas frías',
    'Cosas calientes',
    'Cosas que pican',
    'Cosas que pesan mucho',
    'Cosas blandas',
    'Cosas duras',
    'Cosas que brillan',
    'Cosas pegajosas',
    'Cosas transparentes',
    'Cosas que huelen bien',
    'Cosas que huelen mal',
    'Cosas ruidosas',
    'Cosas afiladas',
    'Cosas suaves',
    'Cosas que dan miedo',
    'Cosas que vuelan',
    'Cosas que flotan en el agua',
    'Cosas con ruedas',
    'Cosas que se enchufan',

    // Graciosas y cercanas
    'Cosas que dan asco',
    'Excusas para llegar tarde',
    'Excusas para no ir a un plan',
    'Cosas que dice tu madre',
    'Cosas que dice tu abuela',
    'Cosas cutres',
    'Cosas que se hacen en verano',
    'Cosas que odias hacer los lunes',
    'Cosas que hay en una fiesta',
    'Cosas que te dan pereza',
    'Cosas que haces cuando te aburres',
    'Cosas que pierdes siempre',
    'Cosas que te hacen llorar',
    'Cosas que hacen ruido por la mañana',
    'Cosas típicas de la Navidad',
    'Cosas que se rompen fácil',
    'Cosas pequeñas que se pierden fácil',
    'Cosas que llevas a la playa',
    'Cosas que se guardan en el bolsillo',
    'Cosas que dan buena suerte',
    'Cosas que haces antes de dormir',
    'Cosas que te compras aunque no necesites',
];
